module.exports = {
  SLOT_STATUS: {
    BOOKED: 'BOOKED',
    CANCELLED: 'CANCELLED',
    REASSIGNED: 'REASSIGNED',
    COMPLETED: 'COMPLETED'
  },
  SITE_STATUS: {
    AVAILABLE: 'AVAILABLE',
    UNAVAILABLE: 'UNAVAILABLE',
  },
  SLOT_UPDATE_TYPE: {
    CANCEL: 'CANCEL',
    REASSIGN: 'REASSIGN',
    COMPLETE: 'COMPLETE'
  }

}