const SLOT_STATUS = {
  BOOKED: 'BOOKED',
  ARRIVED: 'ARRIVED',
  STARTED: 'STARTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REASSIGNED: 'REASSIGNED',
  NOSHOW: 'NOSHOW',
};
const SLOT_UPDATE_TYPE = {
  CANCEL: 'CANCEL',
  REASSIGN: 'REASSIGN',
  COMPLETE: 'COMPLETE',
  ARRIVED: 'ARRIVED',
  STARTED: 'STARTED',
  NOSHOW: 'NOSHOW',
};

module.exports = {
  SLOT_STATUS: SLOT_STATUS,
  SLOT_UPDATE_TYPE: SLOT_UPDATE_TYPE,
  SLOT_TYPE_STATUS_MAP: {
    [SLOT_UPDATE_TYPE.CANCEL]: SLOT_STATUS.CANCELLED,
    [SLOT_UPDATE_TYPE.REASSIGN]: SLOT_STATUS.REASSIGNED,
    [SLOT_UPDATE_TYPE.COMPLETE]: SLOT_STATUS.COMPLETED,
    [SLOT_UPDATE_TYPE.ARRIVED]: SLOT_STATUS.ARRIVED,
    [SLOT_UPDATE_TYPE.STARTED]: SLOT_STATUS.STARTED,
    [SLOT_UPDATE_TYPE.NOSHOW]: SLOT_STATUS.NOSHOW,
  },
  SITE_STATUS: {
    AVAILABLE: 'AVAILABLE',
    UNAVAILABLE: 'UNAVAILABLE',
  },

}